version: "2"
plugins:
  flog:
    enabled: false
    config:
      score_threshold: 34.0
    exclude_patterns:
    - "*/spec/"
  duplication:
    enabled: false
  structure:
    enabled: false
  fixme:
    enabled: true


