version: "2"
checks:
    argument-count:
        enabled: true
    complex-logic:
        enabled: true
    file-lines:
        enabled: true
    method-complexity:
        enabled: true
    method-count:
        enabled: true
    method-lines:
        enabled: true
    nested-control-flow:
        enabled: true
    return-statements:
        enabled: true
    similar-code:
        enabled: true
    identical-code:
        enabled: true
        config:
            threshold: 70
plugins:
  duplication:
    enabled: true
    issue_override:
    severity: info
    config:
      count_threshold: 6
   structure: 
    enabled: true
    issue_override:
    severity: info

