plugins:
  duplication:
    enabled: false
  structure:
    enabled: false
  fixme:
    enabled: true
    issue_override:
      severity: major
  rubocop:
    enabled: false
    channel: rubocop-1-70
