version: "2"
plugins:
  duplication:
    enabled: false
  structure:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-6"
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
  shellcheck:
    enabled: true
    
    
