version: "2"
checks:
    argument-count:
        enabled: false
    complex-logic:
        enabled: false
    file-lines:
        enabled: false
    method-complexity:
        enabled: false
    method-count:
        enabled: false
    method-lines:
        enabled: false
    nested-control-flow:
        enabled: false
    return-statements:
        enabled: false
    similar-code:
        enabled: false
    identical-code:
        enabled: true
        config:
            threshold: 15
plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 16
