plugins:
  brakeman:
    channel: brakeman-5-4-1
    enabled: true
    
    # test
    # test
    # test
    # test
    # test
    # test
    # test
    # test
    # test
    # test
    # test
    # test
    # test
    # test
