version: "2"
checks:
  file-lines:
    config:
    threshold: 150
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/PercentLiteralDelimiters:
        enabled: false
      Rubocop/Style/ClassAndModuleChildren:
        enabled: false
      Rubocop/Style/Documentation:
        enabled: false
      Rubocop/Style/FrozenStringLiteralComment:
        enabled: false
      Rubocop/Metrics/LineLength:
        enabled: true
        Max: 150
exclude_paths:
- config/
- db/
- spec/
- Gemfile
