plugins: 
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      config: .codeclimate.eslintrc.js
  fixme:
    enabled: false
    issue_override:
      severity: blocker
  structure:
    enabled: false
  duplication:
    enabled: false
