version: "2"
checks:
  method-lines:
    config:
      threshold: 100
  argument-count:
    enabled: false
plugins:
  rubocop:
    enabled: true
    channel: "rubocop-0-49"
    checks:
      Rubocop/Style/TrailingCommaInLiteral:
        enabled: false
    config:
      file: "alternate-rubocop-path.yml"
exclude_patterns:
  - "spec/"
  - "!spec/support/helpers"
