plugins:
  brakeman:
    channel: brakeman-6-1-1
    enabled: true
    
    # test
    # test
    # test
    # test
    # test
    # test
    # test
    # test
    # test
    # test
    # test
    # test
    # test
    # test
