engines:
  eslint:
    enabled: true
    config:
      extensions:
      - .es6
      - .js
    checks:
          ember/named-functions-in-promises:
            enabled: false
  duplication:
    enabled: false
  structure:
    enabled: false
ratings:
  paths:
  - "**.js"
exclude_paths:
  - bower_components/*
