engines:
  rubocop:
    enabled: false
  eslint:
    enabled: true
    config:
      ignore_warnings: true
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - ruby:
      - javascript:

ratings:
   paths:
    - "**.rb"
    - "**.go"
    - "**.js"

exclude_paths:
  - spec/**/*
  - vendor/**/*
