config_version = "0"
cli_version = "0.148.0"

[sources.default]
repository = "https://github.com/qltyai/plugins.git"
ref = "v0.11.0-pre"

[runtimes.enabled]
linux = "3.17.1"
node = "19.6.0"
ruby = "3.2.1"

[plugins.enabled]
fixme = "0.0.2"
gitleaks = "8.15.3"
markdownlint = "0.35.0"
prettier = "2.8.4"
rome = "11.0.0"
rubocop = "1.45.1"
